export const NOVELAI = {
  OPEN_WORKBENCH: "open-workbench",
  MINIMIZE: "minimize",
  CLOSE: "close",
  LOAD_CONFIG: "load-config",
  SAVE_CONFIG: "save-config",
  TEST: "test",
  CAPABILITIES: "capabilities",
  MODELS: "models",
  GENERATE: "generate",
  TASKS: "tasks",
  TASK_CANCEL: "task-cancel",
  TASK_RETRY: "task-retry",
  HISTORY: "history",
  GET_IMAGE: "get-image",
  OPEN_OUTPUT: "open-output",
  PICK_IMAGE: "pick-image",
  ASSETS: "assets",
  ASSET_IMPORT: "asset-import",
  ASSET_DELETE: "asset-delete",
  ASSET_UPDATE: "asset-update",
  UPSCALE: "upscale",
  HISTORY_UPDATE: "history-update",
  HISTORY_DELETE: "history-delete",
  TRANSLATE_PROMPT: "translate-prompt",
  TASKS_CHANGED: "tasks-changed",
} as const;
